services:
  postgres:
    image: postgres:16
    container_name: telegram_parser_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_parser
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
