services:
  postgres:
    image: postgres:16
    container_name: telegram_parser_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_parser
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: telegram_parser_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

volumes:
  pgdata:
